dataset: cifar10
model: resnet18
optimizer:
  type: sgd  # Baseline SGD for comparison
  lr: 0.01
  momentum: 0.9
  weight_decay: 5e-4
train:
  batch_size: 256
  epochs: 10
  device: mps
  num_workers: 4
  pin_memory: false
  use_mixed_precision: true
