dataset: cifar10
model: resnet18
optimizer:
  type: zsharp
  rho: 0.05
  percentile: 50  # Reduced percentile to be less aggressive
  lr: 0.01  # Reduced learning rate for stability
  momentum: 0.9
  weight_decay: 5e-4
train:
  batch_size: 128
  epochs: 20  # Reduced epochs for faster testing
  device: mps
  num_workers: 4
  pin_memory: false
  use_mixed_precision: false
