dataset: cifar10
model: resnet18
optimizer:
  type: sgd
  lr: 0.001
  momentum: 0.9
  weight_decay: 5e-4
train:
  batch_size: 128
  epochs: 2
  device: mps
  num_workers: 2
  pin_memory: false
  use_mixed_precision: false
