dataset: cifar10
model: resnet18
optimizer:
  lr: 0.01
  momentum: 0.9
  percentile: 50
  rho: 0.05
  type: zsharp
  weight_decay: 0.0005
train:
  batch_size: 256
  device: mps
  epochs: 10
  num_workers: 4
  pin_memory: false
  use_mixed_precision: true
